### PR TITLE
Monochrome logs is option in functions rather than global parameter

### LINKED ISSUE #99: Move params.monochrome_logs to local scope
Currently, functions like `paramsSummaryLog` uses `params.monochrome_logs` to decide whether to make the logs coloured. I think it's cleaner to move this to local scope and provide it as an input to the function. E.g., from:
```
// params.monochrom_logs = true
paramsSummaryLog()
```

to:
```
// params.monochrom_logs = true
paramsSummaryLog(monochrome = params.monochrome_logs)
```

This would allow pipeline developers to be more flexible about how to handle these things and not rely on a global object. For all we know, someone is out there studying monochrome logs with Nextflow and is frustrated by the confusing parameter.

### PR DESCRIPTION
**Pull request by adamrtalbot**
This changes monochrome logs to being an option in paramsSummaryLog(), paramsSummaryMap() and paramsHelp().

This makes the structure more flexible for pipeline developers who can now use params.monochrome_logs or handle it with their own tooling.

Fixes #99

### CODE REVIEW

**Comment by nvnieuwk** [comment]
I'm all for backwards compatibility! Thanks for the contribution

**Review by nvnieuwk — COMMENTED** [review]
I like this but my main concern is now that we have two positional arguments to the function. This means you have to specify the schema if you want to specify the `monochrome_logs` argument too. 

You can have a look at the `.fromSamplesheet()` factory for an example on how to handle this: https://github.com/nextflow-io/nf-validation/blob/7ca22a47c6504f78fe900cc1caba8bdf927825c4/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L150
(which uses the same method as core nextflow functions with optional arguments)

**Comment by nvnieuwk** [comment]
Yes and some code that looks if the option is supplied like here: https://github.com/nextflow-io/nf-validation/blob/7ca22a47c6504f78fe900cc1caba8bdf927825c4/plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy#L158-L159

**Review by nvnieuwk — COMMENTED** [review]
Thank you I will look at it in detail when I got some more time, it does look very good at first glance though!

**Review by mirpedrol — APPROVED** [review]
LGTM, thank you!
My only comment is that if this is now a parameter from the plugin, we should refactor to `monochromeLogs` to follow the Nextflow convention.

edit: could we refactor the argument name in the `options` map, but allow both parameters `params.monochrome_logs` and `params.monochromeLogs` when retrieving the global parameter? The nf-core template is using `params.monochrome_logs` in other functions, such as creating the logo or formating emails. But other non-nf-core pipelines will use `params.monochromeLogs` as nextflow params are in camelCase

**Comment by mirpedrol** [comment]
> Do you want it in this PR or a separate one?

Can be added to this PR :) Should be a small enough change

**Comment by mirpedrol** [comment]
sounds good!

**Review by nvnieuwk — APPROVED** [review]
LGTM, thanks @adamrtalbot

**Comment by nvnieuwk** [comment]
Oh yes more tests won't hurt anybody :100:

**Pull request merged**
