### PR TITLE
Allow quoted fields for csv files in .fromSamplesheet()

### LINKED ISSUE #62: Feature request: allow quotes strings containing commas in .fromSamplesheet() for .csv files
At this moment, it is not possible to create a channel from a `.csv` file with the `.fromSamplesheet()` function if the `.csv` file contains a quoted field that contains a comma.

```csv
id,path,description
sample1,reads.sample1.fq.gz,"no problems here"
sample2,reads.sample2.fq.gz,"oh no, I cause issues"
```

The line in row 2 will be split on the `no,` as well, which is not the desired behavior.

It should be easy to add this functionality by adding the appropriate parameter value ` quote:true` (https://www.nextflow.io/docs/latest/operator.html#splitcsv) to the following line:

https://github.com/nextflow-io/nf-validation/blob/b040ebbddf55163f61b8a0c22f49d5450146519b/plugins/nf-validation/src/main/nextflow/validation/SamplesheetConverter.groovy#L75

But perhaps it is even a good idea to allow all `.splitCsv` parameters to be passed through as well?

### PR DESCRIPTION
**Pull request by koenbossers**
fixes #62

### CODE REVIEW

**Comment by koenbossers** [comment]
I do not know how to write tests for this feature, so it is probably necessary to add a specific test to the current test suite

**Comment by koenbossers** [comment]
Ready for review!

**Review by nvnieuwk — APPROVED** [review]
LGTM! Thanks for the PR!

**Comment by koenbossers** [comment]
Thanks! I am not allowed to merge, so feel free to do so

**Pull request merged**
