### PR TITLE
New entry exists

### PR DESCRIPTION
**Pull request by mirpedrol**
Returns the non-existing path, does not specify the Entry number.
https://github.com/nextflow-io/nf-validation/pull/40/files#diff-ad3ad6ecbec7c57ccf54e0e62ed9b47a8b513486507e400f9942325fcceeebabL355-R360

Functionality:

- If `exists = true` and the file exists -> validation passes ✅ 
- If `exists = true` and the file doesn’t exist -> validation fails ❌ 
- If `exists = false` or not set -> we don’t check 🚫

### CODE REVIEW

**Comment by ewels** [comment]
I wonder if it's better to just not check if a directory is a directory, if `exists` is false. I think that this usage is non-intuitive.

In other words, treat directory exactly the same as file I guess, unless `exists` is set to true. What do you think @mirpedrol @nvnieuwk ?

**Comment by nvnieuwk** [comment]
> I wonder if it's better to just not check if a directory is a directory, if `exists` is false. I think that the usage here is non-intuitive ☝🏻(whenever something has to be explained in the docs to be used, it's a red flag 😅🚩).
> 
> In other words, treat directory exactly the same as file I guess, unless `exists` is set to true. What do you think @mirpedrol @nvnieuwk ?

Yeah I think it's better to do it like that. I'm not sure how to disable to format check by with a custom schema parameter, maybe we should move the directory checks outside of the traditional validation too?

**Comment by mirpedrol** [comment]
I modified the validation of `directory-path` and it behaves like `path` now. If a directory needs to exist, we can use the `exist` key, otherwise only check if it has a correct path format. Does this look better?

**Comment by nvnieuwk** [comment]
> I modified the validation of `directory-path` and it behaves like `path` now. If a directory needs to exist, we can use the `exist` key, otherwise only check if it has a correct path format. Does this look better?

How about we do check if the path is a directory if it exists? And just skip the check if the path does not exist?

**Review by nvnieuwk — APPROVED** [review]
Awesome thank you!

**Pull request merged**
