### PR TITLE
Pass a parameter name to --help to print the complete information

### PR DESCRIPTION
**Pull request by mirpedrol**
Passing a parameter name to --help will print the complete information for that parameter.

Some examples:

image

image

An exception is returned if the parameter doesn't exist

image

### CODE REVIEW

**Comment by ewels** [comment]
Awesome! I don't think that we need to show `fa_icon` in the terminal (that's just the name of the icon for the web laucher), but otherwise looks brilliant 🚀

**Comment by mirpedrol** [comment]
Thank you @ewels!
Could we merge this PR and #6 if you agree? 
Ping @pditommaso for a review too :)

**Review by ewels — APPROVED** [review]

**Comment by ewels** [comment]
@mirpedrol do you not have permissions to merge PRs yourself? I don't have access to change this, but maybe @pditommaso can upgrade you..

**Comment by mirpedrol** [comment]
> do you not have permissions to merge PRs yourself?

No, I don't see the merge button

**Comment by ewels** [comment]
Ok, I'm not sure how busy @pditommaso is so I'll merge. Feel free to review post-merge @p!

**Pull request merged**
